// Regenerate crawlable catalog markup, metadata, and the shared stylesheet.
// Run with Node after editing dist/app.js, styles.css, or refinements.css.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const dir = path.join(__dirname, 'dist');
const base = 'https://two-brothers-home.pages.dev';
const css=['styles.css','refinements.css','policy.css'].map(p=>fs.readFileSync(path.join(dir,p),'utf8')).join('\n');
const sharedCss=css.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\s+/g,' ').trim();
const source = fs.readFileSync(path.join(dir, 'app.js'), 'utf8');
const nodes = {search:{value:''}, budget:{value:'all'}, sort:{value:'featured'}, 'result-count':{}, 'clear-filters':{}, products:{}};
const context = {document:{getElementById:id=>nodes[id]}};
const products = vm.runInNewContext(source.slice(0, source.indexOf('function setFilter')) + '\nrenderProducts(); products;', context);
let html = fs.readFileSync(path.join(dir, 'index.html'), 'utf8');
const catalog = nodes.products.innerHTML.replaceAll('class="button" data-add=', 'class="button" disabled data-add=');
const catalogBlock = `<!-- catalog:start --><div id="products" class="product-grid">${catalog}</div><!-- catalog:end -->`;
html = /<!-- catalog:start -->/.test(html) ? html.replace(/<!-- catalog:start -->[\s\S]*?<!-- catalog:end -->/, catalogBlock) : html.replace('<div id="products" class="product-grid"></div>', catalogBlock);
html = html.replace(/(<p id="result-count"[^>]*>)[\s\S]*?(<\/p>)/, '$118 products$2');
const schema = {'@context':'https://schema.org', '@graph':[
  {'@type':'WebSite','@id':base+'/#website',url:base+'/',name:'TWO BROTHERS HOME',inLanguage:'en-GH'},
  {'@type':'ElectronicsStore','@id':base+'/#store',name:'TWO BROTHERS HOME',url:base+'/',description:'Independent iPhone and Apple Watch retailer in Kumasi, Ghana, with a pickup point at Dr Wash, Ayensu, UCC, Cape Coast.',address:{'@type':'PostalAddress',streetAddress:'Store No. 24, Blessing House, PZ',addressLocality:'Kumasi',addressCountry:'GH'},areaServed:{'@type':'Country',name:'Ghana'},currenciesAccepted:'GHS',location:{'@type':'Place',name:'Cape Coast pickup point at Dr Wash',address:{'@type':'PostalAddress',streetAddress:'Dr Wash, Ayensu, UCC',addressLocality:'Cape Coast',addressCountry:'GH'}}},
  {'@type':'ItemList',name:'iPhones and Apple Watches at TWO BROTHERS HOME',numberOfItems:products.length,itemListElement:products.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name+' '+p.spec,url:base+'/#'+p.id}))}
]};
const head = `<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>iPhones & Apple Watches in Kumasi | TWO BROTHERS HOME</title>
<meta name="description" content="Compare iPhone and Apple Watch prices in Ghana cedis at TWO BROTHERS HOME. Visit our Kumasi store at PZ or our pickup point at Dr Wash, UCC, Cape Coast.">
<meta name="theme-color" content="#f4f5f3"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${base}/">
<meta property="og:site_name" content="TWO BROTHERS HOME"><meta property="og:title" content="TWO BROTHERS HOME | iPhones & Apple Watches in Ghana"><meta property="og:description" content="Compare prices, choose your upgrade, and visit our Kumasi store or Cape Coast pickup point."><meta property="og:type" content="website"><meta property="og:url" content="${base}/"><meta property="og:locale" content="en_GH"><meta property="og:image" content="${base}/assets/phone-burgundy-realistic-v2.webp"><meta property="og:image:alt" content="Burgundy phone campaign illustration">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="TWO BROTHERS HOME | Your next upgrade"><meta name="twitter:description" content="iPhones and Apple Watches. Clear prices in Ghana cedis. Kumasi store and Cape Coast pickup."><meta name="twitter:image" content="${base}/assets/phone-burgundy-realistic-v2.webp">
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg"><link rel="preload" as="image" href="/assets/phone-burgundy-realistic-v2.webp" fetchpriority="high"><link rel="preload" as="font" href="/assets/dm-sans-400.woff2" type="font/woff2" crossorigin><link rel="preload" as="font" href="/assets/manrope-800.woff2" type="font/woff2" crossorigin><style>${sharedCss}</style>
<script type="application/ld+json">${JSON.stringify(schema)}</script><script src="/app.js" defer></script><script src="/motion.js" defer></script><script src="/phone-display.js" defer></script>`;
html = html.replace(/<head>[\s\S]*?<\/head>/, '<head>'+head+'</head>');
html = html.replace('Clear prices, two local stores, and more choice for your budget.', 'Clear prices, a local store in Kumasi, and a pickup point at Dr Wash, Ayensu, UCC, Cape Coast.');
html = html.replace('Find your nearest store.', 'Visit our Kumasi store or Cape Coast pickup point.');
html = html.replace('Bring your selection to Kumasi or Cape Coast.', 'Review your selection at our Kumasi store, or confirm collection at our Cape Coast pickup point.');
html = html.replace('Delivery rules, charges, timing, warranty, and return terms have not been supplied. Confirm these with the shop before purchasing.', 'Confirm delivery charges, timing, and any device-specific warranty before purchasing. Read our <a href="/refund-policy">refund policy</a> for the process to report a problem or request a return.');
html = html.replace('Enable JavaScript to browse the product catalog and use the shopping bag.', 'You can browse all products and prices below. Enable JavaScript to use filters and the shopping bag.');
let phones = '';
for (let i=0;i<2;i++) {
  phones += `<div class="phone-model phone-model-${i}" role="img" aria-label="Burgundy phone campaign illustration with front, rear and solid metal sides">`;
  for(let depth=-5;depth<=5;depth++) phones += `<span class="phone-shell" style="transform:translateZ(${depth}px)" aria-hidden="true"></span>`;
  for(const side of ['left','right','top','bottom']) phones += `<span class="phone-edge phone-edge-${side}" aria-hidden="true"></span>`;
  for(const face of ['front','back']) {
    const texture = `<span class="phone-texture" aria-hidden="true"></span>`;
    phones += `<span class="phone-face phone-face-${face}" aria-hidden="true">${texture}</span>`;
    if(face==='back') for(let depth=7;depth<=9;depth++) phones += `<span class="phone-face phone-face-back phone-camera" style="transform:rotateY(180deg) translateZ(${depth}px)" aria-hidden="true">${texture}</span>`;
  }
  phones += '</div>';
}
html = html.replace(/<div class="phone-stage">[\s\S]*?<\/figure>/, `<div class="phone-stage">${phones}</div><figcaption>Campaign illustration. Confirm actual colours and condition in store.</figcaption></figure>`);
const policyLinks = '<nav class="policy-links" aria-label="Store policies"><a href="/terms">Terms of service</a><a href="/privacy">Privacy policy</a><a href="/refund-policy">Refund policy</a></nav>';
html = html.replace(/<nav class="policy-links"[\s\S]*?<\/nav>/g, '');
html = html.replace('</footer>',policyLinks+'</footer>');
fs.writeFileSync(path.join(dir,'index.html'),html);
const policies = [
  {slug:'terms',title:'Terms of service',intro:'Clear information for browsing, comparing devices, and visiting TWO BROTHERS HOME.',description:'Terms for using the TWO BROTHERS HOME website, comparing iPhone and Apple Watch prices, and reviewing a selection before visiting our store.',sections:[
    ['Using this website','This website is operated by TWO BROTHERS HOME, an independent retailer in Ghana. It provides product information and a shopping bag to help you compare devices. Apple, iPhone, and Apple Watch are trademarks of their respective owner; this store is not an Apple-owned store.'],
    ['Prices and product information','Prices are listed in Ghana cedis (GH₵ / GHS). Listings show the specifications and prices supplied by the shop and may change. Photos and campaign illustrations are representative and do not confirm a specific device’s colour, condition, accessories, or availability. Confirm the exact product and final price with the shop before purchasing.'],
    ['Your bag and online payments','Adding items to your bag or reviewing a selection does not place an order, reserve stock, or create a purchase agreement. No payment is taken through this website. Your bag is held in the current page session and resets when the page reloads or closes.'],
    ['Purchases and collection','Before paying in store, confirm the exact model, storage or case size, colour, condition, battery health, repair history, included accessories, and any warranty. Our Kumasi store is at Blessing House, PZ, Store No. 24. Confirm pickup arrangements before travelling to Dr Wash, Ayensu, UCC, Cape Coast. Any delivery arrangements and charges must be agreed with the shop.'],
    ['Returns and concerns','Read our <a href="/refund-policy">refund policy</a> for how to raise a device issue or request a return. Device-specific warranty and any additional voluntary return terms should be agreed before purchase. These terms do not exclude rights or remedies available under applicable Ghanaian law.'],
    ['Responsible use','Use the website lawfully. Do not interfere with its operation, attempt unauthorised access, or misuse its content. Links to maps and other third-party services are governed by those providers’ terms and privacy policies.'],
    ['Updates and contact','We may update website information and these terms. The date above identifies this version. To discuss a purchase or these terms, visit TWO BROTHERS HOME at Blessing House, PZ, Store No. 24, Kumasi, Ghana.']
  ]},
  {slug:'privacy',title:'Privacy policy',intro:'What this website handles, what stays on your device, and how to raise a privacy request.',description:'Learn how TWO BROTHERS HOME handles website data, the session shopping bag, Cloudflare hosting, and privacy requests.',sections:[
    ['Who is responsible','TWO BROTHERS HOME is responsible for this storefront. Our contact address is Blessing House, PZ, Store No. 24, Kumasi, Ghana. This notice describes this website’s current functions.'],
    ['Information you provide','The website does not have customer accounts, enquiry forms, online checkout, or payment collection. It does not ask you to submit your name, telephone number, address, or card details. Search terms, filters, and bag selections are processed in your browser and are not submitted as orders. If you discuss a purchase in person, ask the shop how any transaction information will be used before providing it.'],
    ['The shopping bag and cookies','The shopping bag is kept in memory only for the current page session. It resets when you reload or close the page. The storefront code does not set advertising cookies, use local storage for customer profiles, or include marketing tracking scripts. Hosting or security services may process technical information as described below.'],
    ['Hosting and technical data','Cloudflare hosts and delivers this website. When you visit, technical information such as your IP address, requested pages, request time, and browser or device information may be processed to deliver the site, protect it from abuse, and maintain service reliability. Cloudflare may process information outside Ghana. Its handling and retention of service data are described in the <a href="https://www.cloudflare.com/privacypolicy/" rel="noopener">Cloudflare privacy policy</a>. This storefront does not maintain a customer database or a separate record of your shopping bag.'],
    ['External links','Google Maps links open an external service when you choose to follow them. Google then processes data under its own privacy policy. Maps are not embedded on this website.'],
    ['Your privacy requests','You may ask what personal information is held about you and request correction or other applicable remedies under Ghana’s Data Protection Act, 2012 (Act 843). Bring your request to our Kumasi store. We may need information to verify your identity before responding. You may also raise a concern with Ghana’s <a href="https://dpc.gov.gh/for-individuals/" rel="noopener">Data Protection Commission</a>.'],
    ['Changes to this notice','If we introduce checkout, forms, analytics, or other services that collect customer information, we will update this notice to explain those functions. The date above identifies the current version.']
  ]},
  {slug:'refund-policy',title:'Refund policy',intro:'Have a problem with a purchase? Bring the device and purchase details to our Kumasi store.',description:'How to report a device issue, request a return or refund, and confirm purchase-specific terms with TWO BROTHERS HOME in Kumasi.',sections:[
    ['Website selections and payments','This website does not accept payments or create orders. A bag selection can be removed at any time and does not require cancellation or a refund. This policy explains how to raise a concern about a purchase made directly with the shop.'],
    ['Check your device before buying','Before payment, confirm the exact device, colour, condition, battery health, repair history, accessories, and any warranty. Ask the shop to record any additional exchange or return terms on your receipt. A general change-of-mind return period or device warranty duration has not been published; do not assume one from a website listing.'],
    ['How to request help','If you discover a problem or believe a device differs from what was agreed, contact the shop promptly in person at Blessing House, PZ, Store No. 24, Kumasi. Bring the device, its supplied accessories, your receipt or other proof of purchase, and a clear description of the issue. Confirm arrangements with the shop before leaving a device at the Cape Coast pickup point or sending it anywhere.'],
    ['Assessment and resolution','The shop will review the purchase details and the reported issue before confirming whether a repair, replacement, exchange, or refund is appropriate under the agreed sale terms and applicable law. A refund is not confirmed by submitting a request. Any amount, payment method, collection arrangements, and expected timing must be confirmed with the shop after assessment.'],
    ['Protect your information','Back up your data before bringing a device in for assessment. Ask the shop when account sign-out or a device reset is needed for an agreed return. Do not disclose account passwords. Keep a record of your serial number and any handover receipt.'],
    ['Your rights','This policy does not remove or limit rights or remedies available under applicable Ghanaian law. Any voluntary warranty or return terms are additional to those rights. If you disagree with an assessment, ask the shop to review the issue and explain its decision.']
  ]}
];
for(const p of policies){const url=base+'/'+p.slug;const body=p.sections.map(([heading,text],i)=>`<section id="section-${i+1}"><h2>${heading}</h2><p>${text}</p></section>`).join('');fs.writeFileSync(path.join(dir,p.slug+'.html'),`<!doctype html><html lang="en-GH"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${p.title} | TWO BROTHERS HOME</title><meta name="description" content="${p.description}"><link rel="canonical" href="${url}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#f4f5f3"><meta property="og:title" content="${p.title} | TWO BROTHERS HOME"><meta property="og:description" content="${p.description}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><link rel="icon" type="image/svg+xml" href="/assets/favicon.svg"><link rel="stylesheet" href="/site.css"></head><body class="policy-page"><a class="skip" href="#policy-content">Skip to policy</a><header><a class="brand" href="/">TWO BROTHERS <span> HOME</span></a><nav aria-label="Main navigation"><a href="/#catalog">Browse products</a><a href="/#stores">Store & pickup</a></nav></header><main id="policy-content" class="policy-content wrap"><a class="text-link" href="/">← Back to the shop</a><p class="eyebrow">SHOP WITH CLARITY</p><h1>${p.title}</h1><p class="policy-intro">${p.intro}</p><p class="small">Last updated: 29 September 2026</p>${body}<aside class="policy-contact"><h2>Visit us in Kumasi</h2><p>TWO BROTHERS HOME<br>Blessing House, PZ · Store No. 24<br>Kumasi, Ghana</p><a class="text-link" href="/#stores">View store and pickup details →</a></aside></main><footer class="wrap"><a class="brand" href="/">TWO BROTHERS <span> HOME</span></a>${policyLinks}</footer></body></html>`);}
fs.writeFileSync(path.join(dir,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
fs.writeFileSync(path.join(dir,'404.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | TWO BROTHERS HOME</title><meta name="robots" content="noindex"><link rel="stylesheet" href="/site.css"></head><body class="policy-page"><main class="policy-content wrap"><p class="eyebrow">TWO BROTHERS HOME</p><h1>Let’s get you back to the shop.</h1><p>We couldn’t find that page. Explore the collection or visit our store and pickup details.</p><a class="button" href="/">Browse products →</a></main></body></html>`);
fs.writeFileSync(path.join(dir,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...policies.map(p=>p.slug)].map(p=>`<url><loc>${base}/${p}</loc></url>`).join('')}</urlset>\n`);
fs.writeFileSync(path.join(dir,'site.css'),sharedCss+'\n');
console.log('Generated 18 static products, 3 policy pages, metadata, sitemap and shared CSS.');
